<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-03 20:02

import django.db.models.deletion
=======
# Generated by Django 5.0.6 on 2024-06-28 14:18

>>>>>>> 4e13c0e6b073d1bfc4bd300e74baa59a923fff79
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='D.N.I')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=100, verbose_name='Libro')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
                ('fecha', models.DateField(verbose_name='Fecha de compra: ')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Milibreria.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Milibreria.producto')),
            ],
=======
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Precio')),
                ('imagen', models.CharField(max_length=100, null=True, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Contraseña')),
            ],
            options={
                'abstract': False,
            },
>>>>>>> 4e13c0e6b073d1bfc4bd300e74baa59a923fff79
        ),
    ]
