# Generated by Django 5.0.6 on 2024-06-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField(max_length=8, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.IntegerField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('contraseña', models.CharField(max_length=100, unique=True, verbose_name='Contraseña')),
            ],
        ),
    ]
