# Generated by Django 5.0.6 on 2024-07-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=2, verbose_name='Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='libro',
            field=models.ImageField(max_length=200, upload_to='Milibreria/img'),
        ),
    ]
