# Generated by Django 5.0.6 on 2024-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0002_producto_stock_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='libro',
            field=models.ImageField(null=True, upload_to='img_bd/'),
        ),
    ]
