# Generated by Django 5.0.6 on 2024-06-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0002_remove_usuario_contraseña_usuario_contrasenia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasenia',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20, unique=True, verbose_name='Teléfono'),
        ),
    ]
