# Generated by Django 5.0.6 on 2024-07-04 00:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0004_librostock_orden_detalleorden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='total',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Milibreria.libro'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
