# Generated by Django 5.0.6 on 2024-07-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0004_alter_producto_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
        migrations.AlterField(
            model_name='producto',
            name='libro',
            field=models.URLField(null=True, verbose_name='Libro'),
        ),
    ]
