# Generated by Django 5.0.6 on 2024-07-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0005_rename_compras_compra_alter_producto_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cliente',
            field=models.ManyToManyField(through='Milibreria.Compra', to='Milibreria.cliente'),
        ),
    ]
