# Generated by Django 5.0.6 on 2024-07-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0005_remove_orden_total_detalleorden_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='cliente',
            new_name='usuario',
        ),
    ]
