# Generated by Django 5.0.6 on 2024-07-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0006_producto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cliente',
        ),
    ]
