# Generated by Django 5.0.6 on 2024-07-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milibreria', '0006_rename_cliente_orden_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.PositiveIntegerField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.PositiveIntegerField(max_length=20, unique=True, verbose_name='Teléfono'),
        ),
    ]
